2025-01-20 13:25:56,276 - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-01-20 13:25:56,277 - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-01-20 13:26:00,164 - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-01-20 13:26:00,164 - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-01-20 13:26:03,766 - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-01-20 13:26:03,766 - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-01-20 13:26:07,886 - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-01-20 13:26:07,886 - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-01-20 13:26:13,082 - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-01-20 13:26:13,082 - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-01-20 13:26:27,291 - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-01-20 13:26:27,292 - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-01-20 13:26:35,234 - Feedback from 996325952: вв
2025-01-20 13:26:38,647 - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-01-20 13:26:38,647 - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\nkaba\OneDrive\Рабочий стол\mvp_build\venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

